input-output-hk/catalyst-libs

.vscode/settings.recommended.json

Fixes rust analyzer finding the workspace in vscode.

fix(rust): Fix recommended vscode settings for rust-analyzer

---

rust/cardano-chain-follower/src/multi_era_block_data.rs
rust/cardano-chain-follower/src/witness.rs
rust/deny.toml

Makes the Witness interrogation logic public on a MultiEraBlock.

feat(rust/cardano-chain-follower): Make the witness map logic on a MultiEraBlock public.

---

.config/dictionaries/project.dic
.markdownlint.jsonc
Earthfile
docs/Earthfile
integration_tests/rust/Earthfile
integration_tests/rust/overhead_benchmark/README.md
rust/Earthfile
rust/Justfile
rust/c509-certificate/Earthfile
rust/cardano-chain-follower/src/mithril_snapshot_sync.rs
rust/cbork-abnf-parser/tests/testsuite/alternations.rs
rust/cbork/Earthfile
rust/deny.toml
rust/rust-toolchain.toml
rust/rustfmt.toml

This change just bumps CI to use the same branch that cat-voices is using.
It will be changed to a proper version number, once both cat-voices and cat-libs pass CI with it.
* https://github.com/input-output-hk/catalyst-ci/pull/306

chore(general): Bump CI to cat voices ci branch

---

Earthfile
docs/Earthfile
rust/Earthfile
rust/c509-certificate/Earthfile
rust/cbork/Earthfile

* Copy source correctly so cargo/rust changed file detection works as expected.
* Use a common builder, and a builder+src, instead of running rust+INIT twice.
* Don't deliberately break the cache prior to rust building.

fix(rust): test

---

docs/src/catalyst-standards/draft-cips/c509-plutus-restricted-certificate/c509-cert-plutus-restricted.cddl
rust/c509-certificate/examples/cli/main.rs
rust/c509-certificate/src/algorithm_identifier.rs
rust/c509-certificate/src/attributes/attribute.rs
rust/c509-certificate/src/attributes/mod.rs
rust/c509-certificate/src/cert_tbs.rs
rust/c509-certificate/src/extensions/mod.rs
rust/c509-certificate/src/general_names/general_name.rs
rust/c509-certificate/src/general_names/mod.rs
rust/c509-certificate/src/issuer_sig_algo/mod.rs
rust/c509-certificate/src/lib.rs
rust/c509-certificate/src/name/mod.rs
rust/c509-certificate/src/oid.rs
rust/c509-certificate/src/subject_pub_key_algo/mod.rs

Updating outdated doc for c509 certificate crate
https://datatracker.ietf.org/doc/draft-ietf-cose-cbor-encoded-cert/11/
Closes #21

fix(rust/c509-certificate): update docs 

---

.github/workflows/generate-allure-report.yml
rust/Earthfile

Adding allure reporting to repo
Implements [#839](https://github.com/input-output-hk/catalyst-voices/issues/839)
- junit report files saving
- allure report generation
- allure publishing to gh-pages
- adding link to PR with allure link and results
-
-
-

ci(general): Add test reporting to catalyst libs repo

---

rust/cardano-chain-follower/src/metadata/cip509/mod.rs
rust/cardano-chain-follower/src/metadata/cip509/rbac/role_data.rs
rust/cardano-chain-follower/src/metadata/cip509/utils.rs

Add types and utility functions to the public API for RBAC 509 registrations

fix(rust/cardano-chain-follower): Update RBAC 509 API

---

.config/dictionaries/project.dic
.github/workflows/generate-allure-report.yml
rust/Earthfile

Add test coverage for catalyst libs repo
Resolves [#840](https://github.com/input-output-hk/catalyst-voices/issues/840)
Add saving coverage results and uploading to Coveralls [here](https://coveralls.io/github/input-output-hk/catalyst-libs)
-
-
-

ci(general): Add coverage upload

---

rust/cardano-chain-follower/Cargo.toml

Bumps version of the crate to `v0.0.4`.
#56

chore(rust/cardano-chain-follower): Bump crate version to 0.0.4

---

rust/catalyst-voting/Cargo.toml
rust/catalyst-voting/src/crypto/ed25519/decoding.rs
rust/catalyst-voting/src/crypto/group/ristretto255/decoding.rs
rust/catalyst-voting/src/txs/v1/mod.rs
rust/catalyst-voting/src/vote_protocol/committee/decoding.rs
rust/catalyst-voting/src/vote_protocol/committee/mod.rs

Fixed build issues for `catalyst-voting`.
Added missing feature flag`getrandom` for `rand_core` dependency. Updated the way of conversion from `CtOption` to `Option` type to be compatible with the `subtle` version `2.4.1`.
Added missing decoding implementation for some objects.

fix(rust/catalyst-voting): Added missing feature flag, updated conversion from `CtOption` to `Option`

---

docs/src/architecture/08_concepts/catalyst_voting/crypto.md
docs/src/architecture/08_concepts/catalyst_voting/transaction.md
docs/src/architecture/08_concepts/catalyst_voting/tx_v2.cddl
docs/src/architecture/08_concepts/catalyst_voting/tx_v2_cose_payload.cddl

Added a design spec for the catalyst transaction v2.
Docs link:
https://input-output-hk.github.io/catalyst-libs/branch/docs_vote_tx_v2/architecture/08_concepts/catalyst_voting/transaction/#v2
Closes #64

feat(docs): Catalyst vote v2

---

rust/catalyst-voting/Cargo.toml
rust/catalyst-voting/src/vote_protocol/voter/mod.rs

- Added `rayon` lib
- Updated `encrypt_vote` function with the parallel iterator usage.
Performance measurements on `Apple M1`
Old version:
```
vote protocol benchmark/vote encryption
time:   [243.70 µs 243.88 µs 244.14 µs]
```
New version:
```
vote protocol benchmark/vote encryption
time:   [139.87 µs 141.72 µs 144.27 µs]
change: [-42.351% -41.334% -40.375%] (p = 0.00 < 0.05)
Performance has improved.
```

feat(rust/catalyst-voting): Parallel iter usage for `fn encrypt_vote`

---

rust/catalyst-voting/src/crypto/zk_unit_vector/mod.rs

Updated `generate_unit_vector_proof` function with the parallel iterator usage.
Performance measurements on `Apple M1`
Old version:
```
vote protocol benchmark/voter proof generation
time:   [651.54 µs 651.66 µs 651.91 µs]
```
New version:
```
vote protocol benchmark/voter proof generation
time:   [454.23 µs 457.56 µs 464.87 µs]
```

feat(rust/catalyst-voting): Parallel iter usage for `fn generate_unit_vector_proof`

---

rust/vote-tx-v1/src/decoding.rs
rust/vote-tx-v2/Cargo.toml
rust/vote-tx-v2/src/decoding.rs
rust/vote-tx-v2/src/lib.rs

Added a final pieces for the `GeneralisedTx` CBOR decoding functionality.
Closes #75
- Added missing `signature: coset::CoseSign` field with decoding implementation.
- Added missing `event: EventMap` field and underlying structs with decoding implementation.

feat(rust/vote-tx-v2): Finish `GeneralisedTx` CBOR decoding functionality

---

rust/cardano-chain-follower/Cargo.toml
rust/cardano-chain-follower/src/network.rs

- Implemented `time_to_slot` function and added unit tests for the function.
- Increased a version from v0.0.4 to v0.0.5.
Closes #89

feat(rust/cardano-chain-follower): Implement `time_to_slot` function for `Network`

---

rust/rbac-registration/Cargo.toml
rust/rbac-registration/src/cardano/cip509/mod.rs
rust/rbac-registration/src/cardano/cip509/validation.rs
rust/rbac-registration/src/registration/cardano/mod.rs
rust/rbac-registration/src/utils/general.rs

- Create a struct that hold the validation result of CIP509, also include any additional data computed from the validation (currently contains precomputed auxiliary)

fix(rust/rbac-registration): Record CIP509 validation data

---

rust/cardano-chain-follower/Cargo.toml
rust/cardano-chain-follower/src/mithril_snapshot_config.rs

- `mithril-client` version was updated from `0.8.18` to `0.10.4`.
Currently we have [broken builds](https://github.com/input-output-hk/catalyst-libs/actions/runs/12371623752/job/34528128689) in the main branch because of the `mithril-common` update (dependency of `mithril-client`).

fix(rust/cardano-chain-follower): Update mithril-client version (0.8.18 -> 0.10.4)

---

docs/src/architecture/08_concepts/immutable_ledger/cddl/block.cddl
docs/src/architecture/08_concepts/immutable_ledger/cddl/genesis_to_prev_hash.cddl
rust/Earthfile
rust/immutable-ledger/Cargo.toml
rust/immutable-ledger/src/serialize.rs
rust/rbac-registration/src/cardano/cip509/utils/cip134.rs

Replaced `ULID` to `UUID` v7 for the `immutable-ledger` design specs and implementation.

feat(rust/immutable-ledger): Replace `ULID` to `UUID` v7 for `immutable-ledger`

---

.config/dictionaries/project.dic
docs/src/architecture/08_concepts/signed_document_metadata/.pages
docs/src/architecture/08_concepts/signed_document_metadata/metadata.md

Moves documentation for Signed Document Metadata from `catalyst-voices`.

feat(docs): Add documentation for signed document metadata

---

rust/cardano-blockchain-types/Cargo.toml
rust/cardano-blockchain-types/src/slot.rs

Add more functionality to `Slot`

fix(rust/cardano-blockchain-types): add more functionality to `Slot`

---

rust/rbac-registration/src/cardano/cip509/mod.rs
rust/rbac-registration/src/cardano/cip509/rbac/mod.rs
rust/rbac-registration/src/cardano/cip509/types/mod.rs
rust/rbac-registration/src/cardano/cip509/types/tx_input_hash.rs
rust/rbac-registration/src/cardano/cip509/types/validation_signature.rs
rust/rbac-registration/src/cardano/cip509/utils/cip134/mod.rs
rust/rbac-registration/src/cardano/cip509/utils/cip134/uri.rs
rust/rbac-registration/src/cardano/cip509/utils/cip134/uri_set.rs
rust/rbac-registration/src/cardano/cip509/utils/mod.rs
rust/rbac-registration/src/cardano/cip509/validation.rs
rust/rbac-registration/src/cardano/cip509/x509_chunks.rs
rust/rbac-registration/src/lib.rs
rust/rbac-registration/src/registration/cardano/mod.rs

- The `Cip0134UriSet` type was added.
- `Option<Vec<_>>` fields of the `Cip509RbacMetadata` structure were changed to `Vec<_>`.
- Error handling becomes stricter.
Closes https://github.com/input-output-hk/catalyst-libs/issues/104.
I have renamed `Cip0134UriList` to `Cip0134UriSet` because I don't think that "list" is a proper description for the current structure.
This pull request should be merged into the `rbac-registration-improvements` branch instead of `main`. The goal is to have separate smaller incremental changes that can be reviewed together in a separate pull request (from `rbac-registration-improvements` to `main`).

feat(rust/rbac-registration): Introduce Cip0134UriSet type

---

rust/rbac-registration/src/cardano/cip509/rbac/certs.rs
rust/rbac-registration/src/cardano/cip509/utils/cip134/uri_set.rs
rust/rbac-registration/src/registration/cardano/mod.rs

- Store x509 certificates (`Cip509RbacMetadata::x509_certs`) in the decoded format.

feat(rust/rbac-registration): Store decoded x509 certificates

---

rust/rbac-registration/src/cardano/cip509/utils/cip134/uri.rs
rust/rbac-registration/src/cardano/cip509/utils/cip134/uri_set.rs
rust/rbac-registration/src/registration/cardano/mod.rs

- Store and update certificate URIs in the `RegistrationChain` structure.

feat(rust/rbac-registration): Store and update certificate URIs in the registration chain

---

rust/cardano-blockchain-types/src/txn_index.rs

Make `from_saturating` in `TxnIndex` public

fix(rust/cardano-blockchain-types): Expose function in `txn_index`

---

.config/dictionaries/project.dic
rust/Cargo.toml
rust/Earthfile
rust/catalyst-types/Cargo.toml
rust/catalyst-types/src/lib.rs
rust/catalyst-types/src/problem_report.rs

This adds a uniform type to hold comprehensive problem reports that can occur when processing certain data.
These are distinct from hard errors, and are intended to report comprehensive reports to the user about problems 
detected while processing their data.
This is intended to replace the current mutable vec of strings used for such purposes.
As the intention of such report is primarily to report to end users over API's, the report can serialize to json for easy inclusion in HTTP API responses.

feat(rust): Add uniform problem report type

---

rust/catalyst-types/src/problem_report.rs

Add duplicate data error report
where the error contains the value of the duplicate data and its context

feat(rust/catalyst-types): Add duplicate data error report

---

rust/catalyst-types/src/uuid/uuid_v4.rs
rust/catalyst-types/src/uuid/uuid_v7.rs

Derive `serde::Serialize` for `UUIDV4` and `UUIDV7`.

fix(rust/catalyst-types): Add serde::Serialize to UUID types

---

rust/cardano-blockchain-types/src/fork.rs
rust/cardano-blockchain-types/src/multi_era_block_data.rs

Add const, display, and condition check for `Fork`

fix(rust/cardano-blockchain-types): Add const, display, and condition check for `Fork`

---

rust/cbork-utils/Cargo.toml
rust/cbork-utils/src/decode_helper.rs

Update `decode_any` function, make it decode and return bytes for `any` CBOR type.
current implementation make it efficient just to return a CBOR value bytes without deep decode validation of it.
Improved tests to be a property tests.

fix(rust/cbork): Modify `decode_any` function

---

docs/src/architecture/08_concepts/signed_doc/spec.md

Emphasize the validation requirement for the `ver` field

fix(docs): Clarify the `ver` field meaning

---

rust/catalyst-types/src/problem_report.rs

- The `ProblemReport` `Clone` implementation was updated to create a shallow copy that shares the state with the original instance.
Closes https://github.com/input-output-hk/catalyst-libs/issues/157.

feat(rust/catalyst-types): Make ProblemReport to perform a shallow copy on clone

---

rust/cardano-blockchain-types/src/network.rs

- Added indexes to `Network` variants.
- Added `snake_case` when converting variant to string.

feat(rust/cardano-blockchain-types): Add `Network` variants index

---

rust/catalyst-types/Cargo.toml
rust/catalyst-types/src/problem_report.rs

- Added `rc` to the list of serde features for the `catalyst-types` crate.
- Added a test for `ProblemReport` serialization.
Serde provides `Serialize`/`Deserialize` implementations for `Rc<T>` and `Arc<T>` but it is hidden under the `rc` [feature](https://serde.rs/feature-flags.html#rc).

feat(rust/catalyst-types): Add the 'rc' serde feature to catalyst-types in order to be able to serialize ProblemReport

---

rust/catalyst-types/Cargo.toml
rust/catalyst-types/src/uuid/mod.rs
rust/catalyst-types/src/uuid/uuid_v4.rs
rust/catalyst-types/src/uuid/uuid_v7.rs

Updated validation of the `UuidV4` and `UuidV7` types during deserialisation and instantiation.
Needed for https://github.com/input-output-hk/catalyst-libs/pull/155

fix(rust/catalyst-types): Add validation during deserialising and instantiation of the `UuidV4`, `UuidV7`

---

rust/cardano-blockchain-types/src/cip134_uri.rs
rust/cardano-blockchain-types/src/lib.rs
rust/cardano-blockchain-types/src/multi_era_block_data.rs
rust/cardano-blockchain-types/src/slot.rs
rust/cardano-blockchain-types/src/txn_index.rs

- Move the `Cip0134Uri` type to the `cadrano-blockchain-types` crate (from `rbac-registration`)
- Add the `txs` function to `MultiEraBlock`.
- Implement `From<TxnIndex> for usize`.
This is a part of changes from the https://github.com/input-output-hk/catalyst-libs/pull/127/ pull request that is unrelated to the `rbac-registration` crate.

feat(rust/cardano-blockchain-types): Move Cip0134Uri to cadrano-blockchain-types

---

rust/signed_doc/Cargo.toml
rust/signed_doc/src/metadata/document_ref.rs
rust/signed_doc/src/metadata/extra_fields.rs
rust/signed_doc/src/metadata/mod.rs

- Add public getters for `ExtraField` structure.
- Simplify `DocumentRef` structure.
Needed for https://github.com/input-output-hk/catalyst-voices/issues/1539

feat(rust/signed-doc): Improve `catalyst-signed-doc` crate API.

---

rust/catalyst-types/src/cbor_utils.rs
rust/catalyst-types/src/lib.rs
rust/cbork-utils/Cargo.toml
rust/cbork-utils/src/decode_helper.rs

Add `report_duplicated_key` and `report_missing_keys` functions to the `catalyst-types` crate.
https://github.com/input-output-hk/catalyst-libs/pull/178

feat(rust/catalyst-types): Add report_duplicated_key and report_missing_keys functions to catalyst-types

---

rust/cardano-blockchain-types/Cargo.toml
rust/cardano-blockchain-types/src/hashes.rs
rust/cardano-blockchain-types/src/lib.rs

- Add TransactionHash and PubKeyHash types.

feat(rust/cardano-blockchain-types): Add TransactionHash and PubKeyHash types

---

rust/catalyst-types/src/uuid/mod.rs

Make a `uuid::Uuid` dependency import `pub`, so it could be possible to reuse `uuid::Uuid` on the clients code without explicit adding a `uuid` dependency.

feat(rust/catalyst-types): `uuid::Uuid` public import

---

rust/signed_doc/src/metadata/extra_fields.rs
rust/signed_doc/src/metadata/mod.rs

Updated `ExtraFields::from_protected_header` to return `Option<Self>` instead of unused `Result`.
Fixed issue with returning an invalid result when `error_report` argument passed with already predefined some error reports inside it.

fix(rust/signed-doc): Fix `ExtraFields::from_protected_header` error return

---

rust/signed_doc/src/metadata/content_type.rs

Fix content type 
- json -> application/json
- cbor -> application/cbor
Ref: https://www.iana.org/assignments/media-types/media-types.xhtml

fix(rust/signed-doc): Content type

---

rust/signed_doc/Cargo.toml
rust/signed_doc/src/doc_types/mod.rs
rust/signed_doc/src/doc_types/proposal_document.rs
rust/signed_doc/src/lib.rs
rust/signed_doc/src/signature/mod.rs

Removed unneeded `uuid` dep, cleanup API

feat(rust/signed-doc): Remove unneeded `uuid` dep, cleanup API

---

rust/Cargo.toml

Removed unneeded patch of `orx-pseudo-default` as https://github.com/orxfun/orx-pseudo-default/issues/11 resolved

feat(rust): Remove unneeded patch of `orx-pseudo-default`

---

docs/src/architecture/08_concepts/catalyst_docs/comment.md
docs/src/architecture/08_concepts/catalyst_docs/proposal.md
docs/src/architecture/08_concepts/catalyst_docs/review.md
docs/src/architecture/08_concepts/signed_doc/meta.md

- Fixed the part of specifying `template` fields for proposal, comment and review documents.
- Improved description of the comment's `ref`, `reply` fields.
- Added a new `category_id` field for the proposal document.

feat(docs): Update Catalyst Signed Document specification.

---

rust/catalyst-types/src/hash_wrapper.rs

- Implement the `Display` trait for types generated by the `define_hashes!` macro.
`Blake2bHash` implements `Display`, so it makes sense to implement this trait for derived types too. Also it is often used to print a user-friendly hash representation.
https://github.com/input-output-hk/catalyst-voices/pull/1367/

fix(rust/catalyst-types): Implement Display for hash wrappers

---

rust/cardano-blockchain-types/Cargo.toml
rust/cardano-blockchain-types/src/hashes.rs
rust/cardano-blockchain-types/src/lib.rs
rust/cardano-blockchain-types/src/multi_era_block_data.rs
rust/cardano-blockchain-types/src/slot.rs
rust/cardano-blockchain-types/src/txn_output_offset.rs

- Introduce `TxnOutputOffset` type.
- Update `cbork-utils` and `catalyst-types` versions.
- Add `slot` and `enumerate_txs` methods to `MultiEraBlock`.
https://github.com/input-output-hk/catalyst-voices/pull/1367/

fix(rust/cardano-blockchain-types): Introduce 'TxnOutputOffset' type

---

rust/rbac-registration/Cargo.toml

Bump tag for cardano-blockchain-types in rbac-registration

chore(rust/rbac-registration): bump cardano-blockchain-types

---

rust/catalyst-types/src/id_uri/mod.rs
rust/rbac-registration/Cargo.toml
rust/rbac-registration/src/cardano/cip509/cip509.rs
rust/rbac-registration/src/cardano/cip509/validation.rs
rust/rbac-registration/src/registration/cardano/mod.rs
rust/rbac-registration/src/utils/test.rs

- Use the `TransactionHash` type in the `rbac-registration` crate.
- Store `IdUri` in `Cip509`.
https://github.com/input-output-hk/catalyst-voices/pull/1367/

feat(rust/rbac-registration): Use TransactionHash type

---

rust/cardano-blockchain-types/Cargo.toml
rust/cardano-chain-follower/Cargo.toml
rust/catalyst-types/Cargo.toml
rust/rbac-registration/Cargo.toml
rust/signed_doc/Cargo.toml

- Bump cardano-blockchain-types, cardano-chain-follower, catalyst-types, rbac-registration and catalyst-signed-doc versions.
The `r20250218-00` tag that is used in this pull request isn't published yet, so build will fail, but I have checked everything using a branch as a dependency and everything was ok.
https://github.com/input-output-hk/catalyst-voices/pull/1367

chore(general): Bump versions

---

rust/catalyst-types/src/id_uri/mod.rs

- Update `IdUri::is_id` method signature (`&self` instead of `self`).

fix(rust/catalyst-types): IdUri::is_id take self by reference

---

rust/cardano-blockchain-types/src/metadata/cip36/key_registration.rs
rust/cardano-blockchain-types/src/metadata/cip36/mod.rs

Fix doc comments for the `Cip36KeyRegistration` fields

feat(rust/cardano-blockchain-types): Fix comments

---

rust/cardano-blockchain-types/src/metadata/cip36/key_registration.rs
rust/cardano-blockchain-types/src/metadata/cip36/mod.rs
rust/cardano-blockchain-types/src/metadata/cip36/validation.rs

Changing the CIP36 payment address type from `ShelleyAddress` to `Address`
This change will make a stake address a valid payment address, but is not payable.
Shelley address is not payable if the payment part is script.

fix(rust/cardano-blockchain-types): CIP36 payment address type

---

rust/rbac-registration/src/cardano/cip509/mod.rs
rust/rbac-registration/src/cardano/cip509/types/mod.rs
rust/rbac-registration/src/cardano/cip509/types/point_data.rs
rust/rbac-registration/src/registration/cardano/mod.rs

Modify the RBAC registration chain to store historical data.
Closes #235 
- Add new type that store `Point + Transaction Index` with associated `Data`
- `x509_certs`, `c509_certs`, `simple_keys` are now storing historical data where the data is stored Map where key is the array index and the value is Vec <-> Point + Transaction. The last index should be the valid one for the given key index.
- Add `all_role_data` to store the historical data of role data. Since the role data can be partially updated
- Remove the `chain_root_` functions
- The `x509_certs` , `c509_certs`, `simple_keys`, `role_data` type changes

fix(rust/rbac-registration): RBAC reg chain with historical data

---

rust/catalyst-types/src/hashes.rs

Wrong logic for hash length.
Got this error when the length is > the expected hash length
```
thread 'tokio-runtime-worker' panicked at /home/bkioshn/Work/Catalyst/catalyst-libs/rust/catalyst-types/src/hashes.rs:113:14:
copy_from_slice: source slice length (32) does not match destination slice length (16)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: JoinError::Panic(Id(20), "copy_from_slice: source slice length (32) does not match destination slice length (16)", ...)
error: Recipe `run-mithril-download-example-preprod` failed on line 14 with exit code 1
```
Added test to check when given hash length > expected hash length

fix(rust/catalyst-types): Hash length check logic

---

rust/rbac-registration/src/cardano/cip509/types/key_local_ref.rs
rust/rbac-registration/src/registration/cardano/mod.rs

- Implement (derive) the `Copy` trait for `LocalRefInt` and `KeyLocalRef` types.

fix(rust/rbac-registration): Implement (derive) Copy for LocalRefInt and KeyLocalRef

---

rust/cardano-chain-follower/src/follow.rs
rust/cardano-chain-follower/src/mithril_snapshot_iterator.rs

Made a small cleanup of localising applying update for the follower state under one method `update_current`.

chore(rust/cardano-chain-follower): Cleanup updating follower state after getting a new update

---

rust/rbac-registration/src/cardano/cip509/validation.rs

Wrong error log added to error report when role data is empty.
Slot = 87192736
Sending tx with role 0 where x509 and c509 cert (wrong format) has certificate in index 0, and no public key 
**Wrong log  "Only role 0 can contain a certificate at 0 index"** 
```
ProblemReport(State { context: "Decoding and validating Cip509", report: Report([Entry { kind: Other { description: "Unable to decode array value: Error { err: Message, pos: None, msg: \"Name must be an array, text or bytes\" }" }, context: "Cip509RbacMetadata c509 certificates" }, Entry { kind: Other { description: "Only role 0 can contain a certificate at 0 index" }, context: "Role data validation" }]) }) })), network: "preprod"
```
After this fix
```
ProblemReport(State { context: "Decoding and validating Cip509", report: …
```

fix(rust/rbac-registration): empty role data wrong error report

---

rust/signed_doc/src/validator/mod.rs
rust/signed_doc/tests/submission.rs

Validation for  proposal submission action. As defined in the [spec](https://github.com/input-output-hk/catalyst-libs/blob/wip/document-schemas/specs/signed_docs/docs/proposal_submission_action.cue).

feat(rust/signed-doc): Validation and tests for submission action 

---

rust/cardano-chain-follower/src/mithril_snapshot_config.rs

Mithril aggregator updates and changes its public API, so network field is no longer exists under the `beacon` type.
Here is the latest representation of this beacon type
https://github.com/input-output-hk/mithril/blob/4d12aae5bb86779d28094b18c73def2f0997ab95/mithril-common/src/entities/cardano_db_beacon.rs#L10

fix(rust/cardano-chain-follower): Fix mithril snapshot validation

---

rust/rbac-registration/src/cardano/cip509/cip509.rs
rust/rbac-registration/src/cardano/cip509/validation.rs

- Pass the network parameter to `IdUri` constructor  when parsing `Cip509`.

fix(rust/rbac-registration): Pass the (sub)net parameter to IdUri constructor

---

rust/rbac-registration/src/registration/cardano/mod.rs

Added `Clone` to `RegistrationChain` as we are going to add the field in an RBAC token that can hold the pre-queried/built `RegistrationChain`.
[#2123](https://github.com/input-output-hk/catalyst-voices/pull/2123)

feat(rust/rbac-registration): Add `Clone` to `RegistrationChain`

---

rust/rbac-registration/src/registration/cardano/mod.rs

- Remove the Catalyst ID (is_some) check for non-root registrations
A Catalyst ID is present in every registration with role 0, so it isn't always only the root one. The removed check prevents the following (correct) chain to be constructed:
- A first (root) registration with role 0 (has a Catalyst ID).
- A second registration with some other role (there is no Catalyst ID).
- A registration chat updates role 0: it has a Catalyst ID, but it is correct.

fix(rust/rbac-registration): Remove the Catalyst ID (is_some) check for non-root registrations

---

rust/signed_doc/src/providers.rs
rust/signed_doc/src/validator/mod.rs
rust/signed_doc/tests/comment.rs
rust/signed_doc/tests/proposal.rs
rust/signed_doc/tests/submission.rs

- changed validation arguments from `u64` to `Option<Duration>`, so if `None is passed validation is not performed.
- changing the validation from the `id` field to the `ver` field on this time based validation.

fix(rust/signed-doc): Update the Catalyst Signed Document time based validation

---

rust/catalyst-types/Cargo.toml

A new release of the `orx-iterable` transitive crate have a breaking change, which breaks our compilation.

fix(rust): Fixing rust build

---

rust/signed_doc/src/metadata/document_ref.rs
rust/signed_doc/src/validator/rules/category.rs
rust/signed_doc/src/validator/rules/doc_ref.rs
rust/signed_doc/src/validator/rules/reply.rs
rust/signed_doc/src/validator/rules/template.rs
rust/signed_doc/tests/comment.rs
rust/signed_doc/tests/common/mod.rs
rust/signed_doc/tests/proposal.rs
rust/signed_doc/tests/submission.rs

Catalyst Signed Documents `DocumentRef` requires the `ver` field, it is no longer optional.
Closes #270

fix(rust/signed-doc): Update DocumentRef to require version field

---

rust/c509-certificate/src/cert_tbs.rs
rust/rbac-registration/src/cardano/cip509/cip509.rs
rust/rbac-registration/src/cardano/cip509/validation.rs

Add validation for all certificate in RBAC registration should be self-signed (currently only support self-signed)
Note that for self-signed -  issuer == subject, so we can retrieve the subject public key to verify the signature
> Closes https://github.com/input-output-hk/catalyst-voices/issues/2219

feat(rust/rbac-registration): Certificate self-signed validation

---

rust/cardano-chain-follower/Cargo.toml

[`webpki-roots@0.26.9`](https://crates.io/crates/webpki-roots/versions) new version has a breaking change with changed licencing. Stick to the previously used version

fix(rust/cardano-chain-follower): `webpki-roots` crate release breaking change 

---

Earthfile
docs/Earthfile
docs/src/architecture/08_concepts/catalyst_voting/cddl/Earthfile
docs/src/architecture/08_concepts/immutable_ledger/cddl/Earthfile
docs/src/architecture/08_concepts/signed_doc/cddl/Earthfile
rust/Earthfile
rust/c509-certificate/Earthfile
rust/cardano-chain-follower/Cargo.toml
rust/deny.toml
specs/Earthfile
utilities/docs-preview/Earthfile

- Revert locking `webpki-roots`
- updated `cat-ci` with the new `deny.toml` file, allowing new license

feat(rust): Revert locking `webpki-roots`, update `cat-ci`

---

rust/catalyst-types/src/id_uri/key_rotation.rs
rust/rbac-registration/src/cardano/cip509/types/role_data_record.rs
rust/rbac-registration/src/registration/cardano/mod.rs

Refactors the implementation of key rotation values associated with IdUri and RBAC registrations.
Update all occurrences within the `rbac-registration` crate that employ the `usize` type for rotation values (e.g.,
`get_encryption_pk_for_role_at_rotation`,
`get_singing_key_cert_or_key_for_role_at_rotation`) to utilize the newly introduced `KeyRotation` type instead.
Closes #278
Replace `usize` by the dedicated type of the key rotation.
This breaks downstream the calls for `get_encryption_pk_for_role_at_rotation`, `get_singing_key_cert_or_key_for_role_at_rotation`
N/A
N/A

feat(rust/rbac-registration): use KeyRotation

---

rust/cardano-chain-follower/Cargo.toml

New release of `mithril-build-script` crate (0.2.21) https://crates.io/crates/mithril-build-script/versions breaks our build. 
```
error[E0308]: mismatched types
--> /home/dev/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mithril-common-0.4.96/build.rs:10:62
|
10 |     let open_api_code = generate_open_api_versions_mapping(&[Path::new("./"), (Path::new("../"))]);
|                                                              ^^^^^^^^^^^^^^^- help: try using a conversion method: `.to_path_buf()`
|                                                              |
|                                                              expected `PathBuf`, found `&Path`
```

fix(rust/cardano-chain-follower): Fix `cardano-chain-follower` build

---

rust/rbac-registration/src/cardano/cip509/cip509.rs
rust/rbac-registration/src/cardano/cip509/utils/cip134_uri_set.rs
rust/rbac-registration/src/registration/cardano/mod.rs

- Implement the `role_0_stake_addresses` method for both registration chain and `Cip509`.
- Move stake address extraction logic to the `Cip0134UriSet` type.
It is useful to get a list of stake addresses from an individual registration before applying it to the chain.
https://github.com/input-output-hk/catalyst-voices/pull/2454

feat(rust/rbac-registration): Implement role_0_stake_addresses for both registration chain and cip509

---

rust/signed_doc/src/validator/mod.rs
rust/signed_doc/tests/signature.rs

- Added a check under the  `validate_signatures` of the `CatalystSignedDocument`. Verifying that the doc has at least one signature

fix(rust/signed-doc): Catalyst Signed Document missing signature check

---

.vscode/settings.recommended.json
docs/src/architecture/08_concepts/signed_doc/diagrams/all.dot
specs/gen_docs/gen/doc_generator.py
specs/gen_docs/gen/doc_relationship_diagrams.py
specs/gen_docs/gen/graphviz_doc_diagram.py
specs/gen_docs/spec/document.py
specs/gen_docs/spec/signed_doc.py

Just a type annotation cleanup.
No functional changes.

fix(docs): correct python type annotations in documentation generator

---

docs/src/architecture/08_concepts/signed_doc/docs/brand_parameters.md
docs/src/architecture/08_concepts/signed_doc/docs/campaign_parameters.md
docs/src/architecture/08_concepts/signed_doc/docs/category_parameters.md
docs/src/architecture/08_concepts/signed_doc/docs/comment_moderation_action.md
docs/src/architecture/08_concepts/signed_doc/docs/decision_parameters.md
docs/src/architecture/08_concepts/signed_doc/docs/proposal.md
docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment.md
docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_meta_template.md
docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_template.md
docs/src/architecture/08_concepts/signed_doc/docs/proposal_meta_template.md
docs/src/architecture/08_concepts/signed_doc/docs/proposal_moderation_action.md
docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
docs/src/architecture/08_concepts/signed_doc/docs/proposal_template.md
docs/src/architecture/08_concepts/signed_doc/metadata.md
docs/src/architecture/08_concepts/signed_doc/spec.md
docs/src/architecture/08_concepts/signed_doc/types.md
specs/gen_docs/gen/spec_md.py
specs/signed_doc.json
specs/signed_docs/authors_copyright.cue
specs/signed_docs/documentation_links.cue

Clarifies the restrictions in place on validly encoded Catalyst Signed Documents, above and beyond what is defined by COSE Sign.

docs(docs): Better define the document encoding restrictions.

---

rust/signed_doc/src/validator/rules/parameters.rs

Fixing `ParametersRule` implementation and the underlying test, removed not specified for this field checks about the referenced document.

fix(rust/signed-doc): `ParametersRule` impl

---

docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
specs/gen_docs/gen/docs_page_md.py
specs/gen_docs/pyproject.toml
specs/gen_docs/spec/payload.py
specs/gen_docs/uv.lock
specs/signed_doc.json
specs/signed_docs/docs/payload_schemas/proposal_submission_action.draft.example.json
specs/signed_docs/docs/payload_schemas/proposal_submission_action.final.example.json
specs/signed_docs/docs/payload_schemas/proposal_submission_action.hide.example.json
specs/signed_docs/docs/proposal_submission_action.cue
specs/signed_docs/payload.cue

Adds examples for predefined document schemas.
Updates proposal submission action to have such examples defined.

feat(docs):  Add payload examples

---

rust/signed_doc/src/builder.rs
rust/signed_doc/src/lib.rs
rust/signed_doc/tests/decoding.rs

Fixed a new`parameters` field backwards compatibility.
If `category_id`, `campaign_id` or `brand_id` was passed (as an alias of `parameters`) encoding implementation was not symetric with decoding impl (we were lossing original representation).
Closes #344

fix(rust/signed-doc): Preserve original `raw_bytes`

---

rust/signed_doc/Cargo.toml
rust/signed_doc/src/metadata/content_type.rs
rust/signed_doc/src/validator/rules/content_type.rs

- Fixed CBOR validation using `.skip()`
- Moved the validation method and the test from `metadata/content_type.rs` to `validator/rules/content_type.rs`
Closes #348

fix(rust/signed-doc): Correct CBOR content type and data validation

---

rust/signed_doc/tests/comment.rs
rust/signed_doc/tests/proposal.rs
rust/signed_doc/tests/submission.rs

- Added `*_wrong_role` integration test cases. Validate signature validation to the existing one
Part of https://github.com/input-output-hk/catalyst-libs/issues/330

feat(rust/signed-doc): `*_wrong_role` Catalyst Signed Documents integration tests

---

rust/cardano-blockchain-types/src/multi_era_block_data.rs

Fixing a newest nightly` 1.90` lint [`mismatched_lifetime_syntaxes`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_lint/lifetime_syntax/static.MISMATCHED_LIFETIME_SYNTAXES.html) which fails our earthly builds on the empty freshed cache.
```shell
cat-libs-rust+build *failed* |   . error: lifetime flowing from input to output with different syntax can be 
cat-libs-rust+build *failed* | confusing
cat-libs-rust+build *failed* |   .    --> cardano-blockchain-types/src/multi_era_block_data.rs:166:19
cat-libs-rust+build *failed* |   .     |
cat-libs-rust+build *failed* |   . 166 |     pub fn decode(&self) -> &pallas::ledger::traverse::MultiEraBlock {
cat-libs-rust+build *failed* |   .     |                   ^^^^^     ----------------------------------------
cat-libs-rust+build *failed* …
```

fix(rust): Newest `nightly` `1.90` lint `mismatched_lifetime_syntaxes`

---

rust/signed_doc/tests/decoding.rs

Adds test cases for Catalyst Signed Docs:
* Valid minimal metadata fields in document.
* Valid complete metadata fields in document.
This is part of #336

feat(rust/signed-doc): Add tests for minimal and full metadata fields

---

rust/signed_doc/tests/decoding.rs

Addresses test cases defined in #336 .

feat(rust/signed-doc): Valid test cases for doc type and content fields

---

rust/signed_doc/bins/mk_signed_doc.rs
rust/signed_doc/src/decode_context.rs
rust/signed_doc/src/lib.rs
rust/signed_doc/src/metadata/doc_type.rs
rust/signed_doc/src/metadata/document_refs/doc_ref.rs
rust/signed_doc/src/metadata/document_refs/mod.rs
rust/signed_doc/src/metadata/mod.rs
rust/signed_doc/src/metadata/supported_field.rs
rust/signed_doc/src/signature/mod.rs
rust/signed_doc/tests/decoding.rs

- Added `signed_doc_with_strict_deterministic_decoding_wrong_order` and `signed_doc_with_non_strict_deterministic_decoding_wrong_order` test cases.
- Added `signed_doc_with_signatures_non_empty_unprotected_headers` and `signed_doc_with_non_empty_unprotected_headers` test cases.
- Update `CatalystSignedDocument::decode` trait implementation, added `CompatibilityPolicy` as an context argument.
Part of

feat(rust/signed-doc): Added more decoding test cases, cleaned up `DecodeContext`

---

rust/signed_doc/src/signature/mod.rs
rust/signed_doc/tests/decoding.rs

feat(rust/signed-doc): Invalid test cases for protected headers

---

rust/rbac-registration/src/registration/cardano/mod.rs

- Add the `current_txn_index` method to the `RegistrationChain` type.
https://github.com/input-output-hk/catalyst-voices/pull/2979

fix(rust/rbac-registration): Add the 'current_txn_index' method to the RegistrationChain type

---

rust/catalyst-types/src/catalyst_id/mod.rs
rust/rbac-registration/src/registration/cardano/mod.rs

Wrap `CatalystId` fields into `Arc`. This type is relatively "heavy" and often stored or passed around, so it makes sense to use `Arc` internally.
Related to https://github.com/input-output-hk/catalyst-voices/issues/2980.

feat(rust/catalyst-types): Wrap Catalyst ID fields into Arc

---

rust/signed_doc/src/metadata/doc_type.rs

- Added convenient trait implementations for the `DocType`
- Removed redundant `doc_types` method

feat(rust/signed-doc): Convenient trait implementations for `DocType`

---

rust/signed_doc/src/metadata/doc_type.rs

Added a function to convert back `DocType` to deprecated UUID
[#3063](https://github.com/input-output-hk/catalyst-voices/pull/3063)

feat(rust/signed-doc): Add a function to convert back `DocType` to deprecated UUID

---

rust/catalyst-types/src/uuid/mod.rs
rust/catalyst-types/src/uuid/uuid_v4.rs
rust/catalyst-types/src/uuid/uuid_v7.rs
rust/signed_doc/src/doc_types/mod.rs
rust/signed_doc/src/lib.rs
rust/signed_doc/src/metadata/doc_type.rs
rust/signed_doc/src/metadata/mod.rs
rust/signed_doc/src/metadata/supported_field.rs
rust/signed_doc/src/validator/mod.rs
rust/signed_doc/tests/comment.rs
rust/signed_doc/tests/decoding.rs
rust/signed_doc/tests/proposal.rs
rust/signed_doc/tests/submission.rs

Revert back to the original definition of the `type` metadata field, to be a single `UUIDv4` instead of of array of uuids
Related to https://github.com/input-output-hk/catalyst-libs/issues/330

feat(rust/signed-doc): Revert back to the original `DocType` format

---

.github/workflows/validate-project-fields.yml

- Add workflow for project fields validation to ensure the repository follows our project management standards.
> Note for the reviewer: The script automatically assigns PRs to the PR creator using the GitHub REST API, which requires write permissions.

ci(general): add project fields validation

---

rust/rbac-registration/src/cardano/cip509/cip509.rs
rust/rbac-registration/src/cardano/cip509/types/role_data.rs
rust/rbac-registration/src/cardano/cip509/utils/cip19.rs
rust/rbac-registration/src/cardano/cip509/validation.rs
rust/rbac-registration/src/registration/cardano/mod.rs

- Fix (some) logging (use `Display` instead of `Debug` for hashes).
- Remove verbose logging in `RegistrationChain::new` and `RegistrationChain::update` functions.

fix(rust/rbac-registration): Fix some RBAC logging

---

rust/cardano-chain-follower/Cargo.toml

Bumping a `cardano-chain-follower` crate version to make a new release for it

chore(rust/cardano-chain-follower): Bump `cardano-chain-follower` version

---

rust/signed_doc/Cargo.toml
rust/signed_doc/src/metadata/content_type.rs
rust/signed_doc/src/validator/rules/content_type.rs
rust/signed_doc/src/validator/rules/template.rs

- Added more supporting media types
Closes #411

feat(rust/signed-doc): Add more supporting media types

---

specs/Earthfile
specs/Justfile

fix(docs): fix local builds with earthly and Just

---

Earthfile
docs/Earthfile
docs/src/architecture/08_concepts/catalyst_voting/cddl/Earthfile
docs/src/architecture/08_concepts/immutable_ledger/cddl/Earthfile
docs/src/architecture/08_concepts/signed_doc/cddl/Earthfile
rust/Earthfile
rust/c509-certificate/Earthfile
specs/Earthfile
specs/generators/pages/signed_doc/cddl/Earthfile.jinja
utilities/docs-preview/Earthfile

Bumped `cat-ci` version to the most recent one `v3.5.12`. Solving rust builder issue with `refinery` tool build
```
rust-tools+tool-refinery |   --> /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/time-0.3.28/src/format_description/parse/mod.rs:83:9
rust-tools+tool-refinery |    |
rust-tools+tool-refinery | 83 |     let items = format_items
rust-tools+tool-refinery |    |         ^^^^^
rust-tools+tool-refinery | ...
rust-tools+tool-refinery | 86 |     Ok(items.into())
rust-tools+tool-refinery |    |              ---- type must be known at this point
rust-tools+tool-refinery |    |
rust-tools+tool-refinery | help: consider giving `items` an explicit type, where the placeholders `_` are specified
rust-tools+tool-refinery |    |
rust-tools+tool-refinery | 83 |     let items: …
```

chore(general): bump cat-ci versions to `v3.5.12`

---

rust/catalyst-signed-doc-macro/src/rules/mod.rs
rust/signed_doc/src/validator/mod.rs
rust/signed_doc/src/validator/rules/mod.rs
rust/signed_doc/src/validator/rules/original_author.rs

Implements the functional validation of a new doc version that verifies that the authors of the previous (latest) version are exactly the same.
Current specifications do not clearly state what the validation of author signatures should involve. For example, does signature order matter? can there be new authors?
Closes #492 .

feat(rust/signed-doc): Add validation rule to check authors of new doc version match previous those in version.

---

rust/catalyst-signed-doc-macro/src/rules/doc_ref.rs
rust/catalyst-signed-doc-macro/src/rules/mod.rs
rust/catalyst-signed-doc-macro/src/signed_doc_spec.rs
rust/catalyst-signed-doc-macro/src/signed_doc_spec/doc_ref.rs
rust/catalyst-signed-doc-macro/src/signed_doc_spec/mod.rs

Added macro `RefRule` auto instantiation based on the `signed_doc.json` specification file.
Closes https://github.com/input-output-hk/catalyst-libs/issues/513

feat(rust/signed-doc): `RefRule` auto generation

---

rust/signed_doc/src/builder.rs
rust/signed_doc/src/lib.rs
rust/signed_doc/src/metadata/mod.rs
rust/signed_doc/src/validator/rules/content.rs
rust/signed_doc/src/validator/rules/content_type.rs
rust/signed_doc/tests/decoding.rs

Updated decoding logic of Catalyst Signed Document, `content-type` metadata field could be optional, not required field.
Related to https://github.com/input-output-hk/catalyst-internal-docs/issues/266
- Changed `doc_content_type` method
- Removed verification that `content-type` should be present during decoding logic
- Fixed decoding tests

feat(rust/signed-doc): Not required `content-type` during decoding

---

rust/catalyst-signed-doc-macro/src/rules/mod.rs
rust/signed_doc/src/builder.rs
rust/signed_doc/src/content.rs
rust/signed_doc/src/lib.rs
rust/signed_doc/src/signature/mod.rs
rust/signed_doc/src/validator/mod.rs
rust/signed_doc/src/validator/rules/content.rs
rust/signed_doc/src/validator/rules/mod.rs
rust/signed_doc/src/validator/rules/template.rs
rust/signed_doc/src/validator/rules/utils.rs
rust/signed_doc/tests/decoding.rs

Refactor and slightly update the current `ContentRule` by splitting it into two validation types `ContentRule` and `TemplateRule` following the latest comment from the issue ticket https://github.com/input-output-hk/catalyst-libs/issues/537#issuecomment-3258071236
Closes https://github.com/input-output-hk/catalyst-libs/issues/537

feat(rust/signed-doc): Split into two `ContentRule` and `TemplateRule`

---

rust/catalyst-types/Cargo.toml
rust/catalyst-types/src/catalyst_id/role_index.rs

Define a new Admin roles as part of the `enum RoleId`.
Part of https://github.com/input-output-hk/catalyst-internal-docs/issues/266

feat(rust/catalyst-types): Admin roles for the `RoleId` enum

---

rust/signed_doc/src/validator/mod.rs
rust/signed_doc/src/validator/rules/parameters.rs
rust/signed_doc/src/validator/rules/section.rs

Updating the existing validation rules initialisation for the `Proposal`, `Comment` and `Proposal Submission Action` documents.

feat(rust/signed-doc): Signed Document validation rules change
