input-output-hk/catalyst-libs

- .github/workflows/ci.yml
- blueprint.cue
- docs/blueprint.cue
- rust/blueprint.cue
- rust/c509-certificate/Earthfile
- rust/c509-certificate/blueprint.cue
- rust/cardano-chain-follower/src/metadata/cip509/decode_helper.rs
- rust/cbork/Earthfile
- rust/cbork/blueprint.cue
> ci(general): migrates to forge

- .github/workflows/ci.yml
> ci(general): locks version and updates events

- rust/cardano-chain-follower/src/metadata/cip509/mod.rs
Exposing the RBAC and X509 chunk module
> fix(rust/cardano-chain-follower): expose ciip509 mod

- .github/workflows/generate-allure-report.yml
Just adding new workflow for allure reports. 
It needs to land on main so it can be worked on a branch later on as part of task [#839](https://github.com/input-output-hk/catalyst-voices/issues/839)
Prepares [#839](https://github.com/input-output-hk/catalyst-voices/issues/839)
New workflow needs to land on main so it can be worked on a branch later on as part of task [#839](https://github.com/input-output-hk/catalyst-voices/issues/839)
-
-
-
> ci(general): Add new workflow for allure report

- .config/dictionaries/project.dic
- .github/workflows/ci.yml
> ci(general): bumps to v1.1.0

- rust/cardano-chain-follower/examples/follow_chains.rs
- rust/cardano-chain-follower/src/follow.rs
Closes input-output-hk/catalyst-engineering-internal#1
> fix(rust/cardano-chain-follower): Check condition for Block Roll Forward

- .config/dictionaries/project.dic
- docs/src/architecture/08_concepts/catalyst_voting/.pages
- docs/src/architecture/08_concepts/catalyst_voting/crypto.md
- docs/src/architecture/08_concepts/catalyst_voting/transaction.md
- docs/src/architecture/08_concepts/catalyst_voting/tx_v1.abnf
- rust/catalyst-voting/src/crypto/group/mod.rs
- rust/catalyst-voting/src/crypto/zk_dl_equality.rs
- rust/catalyst-voting/src/crypto/zk_unit_vector/mod.rs
- rust/catalyst-voting/src/crypto/zk_unit_vector/polynomial.rs
- rust/catalyst-voting/src/txs/v1/mod.rs
- rust/catalyst-voting/src/vote_protocol/mod.rs
- rust/catalyst-voting/src/vote_protocol/tally/mod.rs
- rust/catalyst-voting/src/vote_protocol/tally/proof.rs
- rust/catalyst-voting/src/vote_protocol/voter/mod.rs
- rust/catalyst-voting/src/vote_protocol/voter/proof.rs
Moved docs from the `catalyst-voices` repo.
Update links in `catalyst-voting` crate code.
> feat(docs): Moved catalyst-voting specific docs from the `catalyst-voices` repo

- rust/cardano-chain-follower/Cargo.toml
Bump `cardano-chain-follower` version to `0.0.6`.
> fix(rust/cardano-chain-follower): Bump version to v0.0.6

- .github/workflows/ci.yml
- .github/workflows/generate-allure-report.yml
This PR make the allure test report run after the CI has finished
> test(general): make allure reports run after ci

- rust/catalyst-types/src/problem_report.rs
Add `ConversionError` in `ProblemReport`
> fix(rust/catalyst-types): add conversion error in problem report

- .github/workflows/ci.yml
- .github/workflows/generate-allure-report.yml
> chore(general): update-forge-cli-to-1.5.1

- rust/cardano-chain-follower/Cargo.toml
Tagged `catalyst-types` in `cardano-chain-follower`
> fix(rust/cardano-chain-follower): tagged `catalyst-types` in `cardano-chain-follower`

- rust/signed_doc/Cargo.toml
- rust/signed_doc/README.md
- rust/signed_doc/examples/mk_signed_doc.rs
- rust/signed_doc/src/builder.rs
- rust/signed_doc/src/content.rs
- rust/signed_doc/src/lib.rs
- rust/signed_doc/src/metadata/additional_fields.rs
- rust/signed_doc/src/metadata/algorithm.rs
- rust/signed_doc/src/metadata/content_encoding.rs
- rust/signed_doc/src/metadata/document_id.rs
- rust/signed_doc/src/metadata/document_ref.rs
- rust/signed_doc/src/metadata/document_type.rs
- rust/signed_doc/src/metadata/document_version.rs
- rust/signed_doc/src/metadata/extra_fields.rs
- rust/signed_doc/src/metadata/mod.rs
- rust/signed_doc/src/signature/mod.rs
Serialize Catalyst Signed Documents into CBOR, and fix example CLI tool to build, sign and inspect signed documents.
#154
> feat(rust/signed-doc): Serialize Signed Documents in CLI tool

- rust/signed_doc/Cargo.toml
- rust/signed_doc/examples/mk_signed_doc.rs
- rust/signed_doc/src/builder.rs
- rust/signed_doc/src/content.rs
- rust/signed_doc/src/lib.rs
- rust/signed_doc/src/metadata/content_type.rs
- rust/signed_doc/src/metadata/document_ref.rs
- rust/signed_doc/src/metadata/mod.rs
- rust/signed_doc/src/signature/mod.rs
> feat(rust/signed-doc): Add signing and verification logic to Catalyst Signed Docs

- rust/signed_doc/src/metadata/content_type.rs
Improving error message for `ContentType`
> fix(rust/signed-doc): Improving error message for `ContentType`

- rust/Cargo.toml
- rust/Earthfile
- rust/deny.toml
Same fix as https://github.com/input-output-hk/catalyst-voices/pull/1808
> fix(rust): Fix rust build

- rust/cardano-chain-follower/Cargo.toml
- rust/signed_doc/Cargo.toml
- Update `cardano-blockchain-types` and `catalyst-types` versions for `cardano-chain-follower`.
- Update `rbac-registration` and `catalyst-types` versions for `signed_doc`.
https://github.com/input-output-hk/catalyst-voices/pull/1367
> chore(general): Update catalyst-libs dependencies for chain follower and signed doc

- rust/cardano-blockchain-types/Cargo.toml
- rust/cardano-chain-follower/Cargo.toml
- rust/rbac-registration/Cargo.toml
- rust/signed_doc/Cargo.toml
Bump crates get rid from the `fmmap 0.3.3` version
> feat(rust): Bump crates, get rid of the `fmmap 0.3.3` version 

- rust/cardano-blockchain-types/Cargo.toml
- rust/cardano-chain-follower/Cargo.toml
- rust/rbac-registration/Cargo.toml
- rust/signed_doc/Cargo.toml
Replace `path` dependencies with specifying `tag`
> fix(rust): Replace path with tag

- rust/cardano-blockchain-types/Cargo.toml
- rust/cardano-blockchain-types/src/txn_index.rs
- rust/cardano-chain-follower/Cargo.toml
- rust/rbac-registration/Cargo.toml
- rust/rbac-registration/src/registration/cardano/mod.rs
- rust/signed_doc/Cargo.toml
- Added additional validation for `RegistrationChain`
- Added `From<TxnIndex> for u16` impl
- Moved from tagging to "path" dependency specification
> feat(rust):  `RegistrationChain` additional validation, added `From<TxnIndex> for u16`

- rust/cardano-blockchain-types/src/metadata/cip36/mod.rs
- rust/cardano-chain-follower/src/chain_sync.rs
- Derive the `Debug` trait for `Cip36`.
It is really helpful for debugging to be able to print a structure.
> feat(rust/cardano-blockchain-types): Implement (derive) Debug for Cip36

- .github/workflows/ci.yml
- .github/workflows/semantic_pull_request.yml
Run CI when PR is opened.
**Previous behavior:**
When PR is opened, the CI doesn't run. To fix this, need to convert to draft then convert back to ready for review.
Hence, this PR solved the issue.
> chore(general): Run CI when PR is opened

- rust/rbac-registration/src/registration/cardano/mod.rs
- Store Catalyst ID in the registration chain.
> fix(rust/rbac-registration): Store Catalyst ID in the registration chain

- rust/signed_doc/src/lib.rs
During `CatalystSignedDocument ` CBOR decoding allow both CoseSign tagged and untagged encoded bytes.
Encoding `CatalystSignedDocument` returns only CoseSign tagged bytes.
> feat(rust/signed-doc): Update `CatalystSignedDocument` decoding/encoding

- rust/rbac-registration/src/cardano/cip509/types/role_number.rs
- Implement conversion from `RoleNumber` to `u8`.
> feat(rust/rbac-registration): Implement 'From<RoleNumber> for u8'

- rust/signed_doc/src/validator/rules/signature_kid.rs
Improved report message for `SignatureKidRule::check`
> feat(rust/signed-doc): `SignatureKidRule` improve report message

- docs/src/architecture/08_concepts/signed_doc/docs/brand_parameters.md
- docs/src/architecture/08_concepts/signed_doc/docs/campaign_parameters.md
- docs/src/architecture/08_concepts/signed_doc/docs/category_parameters.md
- docs/src/architecture/08_concepts/signed_doc/docs/comment_moderation_action.md
- docs/src/architecture/08_concepts/signed_doc/docs/election_parameters.md
- docs/src/architecture/08_concepts/signed_doc/docs/proposal.md
- docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment.md
- docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_meta_template.md
- docs/src/architecture/08_concepts/signed_doc/docs/proposal_comment_template.md
- docs/src/architecture/08_concepts/signed_doc/docs/proposal_meta_template.md
- docs/src/architecture/08_concepts/signed_doc/docs/proposal_moderation_action.md
- docs/src/architecture/08_concepts/signed_doc/docs/proposal_submission_action.md
- docs/src/architecture/08_concepts/signed_doc/docs/proposal_template.md
- specs/gen_docs/gen_docs_page_md.py
- specs/signed_doc.json
Added more context to replace TODO mesages
> fix(docs): Updated TODO place holder text with context

- .github/workflows/ci.yml
- .github/workflows/generate-allure-report.yml
Consolidate all the forge version bumps for 1.7.2 into one PR.
> chore(deps): bump input-output-hk/catalyst-forge/actions/* from 1.7.1 to 1.7.2

- rust/catalyst-types/src/catalyst_id/mod.rs
Improve the test coverage of catalyst id parse by adding more checks.
N/A
N/A
N/A
N/A
#302
> refactor(rust/catalyst-types): improve catalyst id parse test coverage

- rust/rbac-registration/src/cardano/cip509/cip509.rs
- rust/rbac-registration/src/registration/cardano/mod.rs
Change reference cip509 in Reg chain new and update
> fix(rust/rbac-registration): Change reference cip509 in Reg chain new and update

- rust/signed_doc/src/metadata/extra_fields.rs
Logic is maintained while code condensed and seems simpler. 
Couldn't make a classic gh suggestion, because the code spans deleted lines.
#317
* [x I have performed a self-review of my code
> style(rust/signed-doc): simplified iterator call chain

- rust/rbac-registration/src/registration/cardano/mod.rs
- Store a point of the latest transaction in `RegistrationChain`.
In the RBAC endpoint implementation we need to know last stable slot. This allows to get it from a registration chain object.
https://github.com/input-output-hk/catalyst-voices/pull/2568
> feat(rust/rbac-registration): Store a point of the latest transaction in RegistrationChain

- rust/signed_doc/tests/decoding.rs
- Added test cases for random kid and case-insensitive `content_encoding`
#336
> test(rust/signed-doc): Add test cases for random kid, invalid COSE tag, and case-insensitive `content_encoding`

- rust/signed_doc/src/metadata/content_type.rs
- rust/signed_doc/src/validator/rules/content_type.rs
- rust/signed_doc/src/validator/rules/template.rs
- Added `application/cddl`
- Added `application/json+schema`
- Updated corresponding test
!!NOTE!! The validation logic needs to be implemented separately
Closes #375
> feat(rust/signed-doc): Add new `ContentType` variants: `Cddl` and `JsonSchema`

- .github/workflows/ci.yml
- .github/workflows/generate-allure-report.yml
Bumping catalyst-forge version to ci/v1.7.4 for fixing our earthly dependent CI workflows
> fix(general): Bumping catalyst-forge version

- .config/dictionaries/project.dic
- .github/workflows/ci.yml
- .github/workflows/generate-allure-report.yml
- blueprint.cue
> ci(general): bumps forge to v0.19.1 and ci to v1.8.1

- rust/cardano-blockchain-types/Cargo.toml
Update cardano blockchain type version
> fix(rust/cardano-blockchain-types): Update cardano blockchain type version

- rust/cardano-blockchain-types/Cargo.toml
- rust/cardano-chain-follower/Cargo.toml
- rust/catalyst-types/Cargo.toml
- rust/rbac-registration/Cargo.toml
- rust/signed_doc/Cargo.toml
Releasing a new version of the `catalyst-types` crate
> feat(general): `catalyst-types` version `0.0.5`

- rust/cardano-blockchain-types/Cargo.toml
- rust/signed_doc/Cargo.toml
Bump `catalyst-signed-doc` crate version to `0.0.5`
> feat(general): `catalyst-signed-doc` version `0.0.5`

- rust/cardano-chain-follower/Cargo.toml
- rust/rbac-registration/Cargo.toml
Bumping `rbac-registration` crate version to `0.0.6`
> feat(general): `rbac-registration` version `0.0.6`
